apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-aws-operator
  namespace: kube-system
  labels:
    app.kubernetes.io/name: k8s-aws-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-aws-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-aws-operator
    spec:
      serviceAccountName: k8s-aws-operator
      containers:
      - image: logmein/k8s-aws-operator
        name: k8s-aws-operator
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            memory: 100Mi
        args:
        - -region=us-east-1
        - -leader-election-namespace=kube-system
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
